<?php
$form = $this->form;
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'Add User'=>$this->url('users',['action' => 'add']),
]);


?>
<h1>Add user</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?php
            $formObj = $this->form();
            echo $formObj->openTag($form);
        ?>

        <div class="form-group">
            <?php
                $emailInput = $form->get('email');
                $emailInput->setAttributes([
                    'class' => 'form-control',
                    'placeholder' => 'name@example.com'
                ]);

            ?>
            <?= $this->formLabel($emailInput); ?>
            <?= $this->formElement($emailInput); ?>
            <?= $this->formElementErrors($emailInput); ?>
        </div>


        <div class="form-group">
            <?php
            $fullName = $form->get('full_name');
            $fullName->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Vasia Pupkin'
            ]);

            ?>
            <?= $this->formLabel($fullName); ?>
            <?= $this->formElement($fullName); ?>
            <?= $this->formElementErrors($fullName); ?>
        </div>

        <div class="form-group">
            <?php
            $password = $form->get('password');
            $password->setAttributes([
                'class' => 'form-control'
            ]);

            ?>
            <?= $this->formLabel($password); ?>
            <?= $this->formElement($password); ?>
            <?= $this->formElementErrors($password); ?>
        </div>

        <div class="form-group">
            <?php
            $passwordConfirm = $form->get('confirm_password');
            $passwordConfirm->setAttributes([
                'class' => 'form-control'
            ]);

            ?>
            <?= $this->formLabel($passwordConfirm); ?>
            <?= $this->formElement($passwordConfirm); ?>
            <?= $this->formElementErrors($passwordConfirm); ?>
        </div>

        <div class="form-group">
            <?php
            $status = $form->get('status');
            $status->setAttributes([
                'class' => 'form-control'
            ]);

            ?>
            <?= $this->formLabel($status); ?>
            <?= $this->formElement($status); ?>
            <?= $this->formElementErrors($status); ?>
        </div>

        <?php
            $submit = $form->get('submit');
            $submit->setAttributes([
                'class'=>'btn btn-primary'
            ]);
        ?>
        <?= $this->formElement($form->get('submit')); ?>



        <?= $this->form()->closeTag(); ?>
    </div>
</div><!--/row -->