<?php
$form = $this->form;
$user = $this->user;
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'Change password'=>$this->url('users',['action' => 'change-password', 'id' => $user->getId()]),
]);

$form->prepare();

?>
<h1>Change password for user <?= $user->getEmail();?></h1>

<div class="row">
    <div class="col-md-6">
        <?php
            $formObj = $this->form();
            echo $formObj->openTag($form);
        ?>

        <div class="form-group">
            <?php
                $oldPass = $form->get('old-password');
                $oldPass->setAttributes([
                    'class' => 'form-control',
                    'placeholder' => 'Enter old password'
                ]);

                echo $this->formLabel($oldPass);
                echo $this->formElement($oldPass);
                echo $this->formElementErrors($oldPass);
            ?>
        </div>


        <div class="form-group">
            <?php
            $newPass = $form->get('new-password');
            $newPass->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Enter new password'
            ]);

            echo $this->formLabel($newPass);
            echo $this->formElement($newPass);
            echo $this->formElementErrors($newPass);
            ?>
        </div>


        <div class="form-group">
            <?php
            $confirmPass = $form->get('confirm-new-password');
            $confirmPass->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Confirm new password'
            ]);
            echo $this->formLabel($confirmPass);
            echo $this->formElement($confirmPass);
            echo $this->formElementErrors($confirmPass);

            ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>

        <?php
            $submit = $form->get('submit');
            $submit->setAttributes(['class' => 'btn btn-primary']);
            echo $this->formElement($submit);
        ?>

        <?= $formObj->closeTag(); ?>
    </div>
</div>