<?php
$form = $this->form;
$this->headTitle('Reset password');

$form->prepare();

?>


<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?php
            $formHelper = $this->form();
            echo $formHelper->openTag($form);
        ?>
        <h1>Reset password</h1>
        <p>Enter you e-mail address blow to reset your password</p>

        <?php
            $emailElement = $form->get('email');
            $emailElement->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Email address'
            ]);

            echo $this->formElement($emailElement);
            echo $this->formElementErrors($emailElement);
        ?>
        <?php
        $captcha = $form->get('captcha');

        echo $this->formElement($captcha);
        echo $this->formElementErrors($captcha);
        ?>
        <p class="hint">Enter the letters above as you see them.</p>

        <?php
        $csrf = $form->get('csrf');
        echo $this->formElement($csrf);
        ?>

        <?php
        $submit = $form->get('submit');
        $submit->setAttributes([
            'class' => 'btn btn-large btn-primary'
        ]);


        echo $this->formElement($submit);
        ?>



        <?= $formHelper->closeTag(); ?>
    </div>
</div>