version: '2'
services:
  zf-user:
      build: .
      image: zf-user
      container_name: zf-user
      environment:
          XDEBUG_CONFIG: remote_host=10.0.2.15
      ports:
          - "80:80"
      volumes:
          - "../:/var/www/site"
      restart: always
