version: '2'
services:
   maria-zf-user:
      image: mariadb
      container_name: maria-zf-user
      ports:
          - "3306:3306"
      volumes:
          - "./.data/db:/var/lib/mysql:rw"
      restart: always
      environment:
         - "MYSQL_USER=root"
         - "MYSQL_ROOT_PASSWORD=mysql"